version: "3"

dotenv:
  - .env

tasks:
  tidy:
    cmd: go mod tidy

  sqlc:
    cmds:
      - sqlc generate
      - task: tidy 

  proxyproto:
    cmds:
      - protoc -I ./contracts proxyproto.proto --go_out=./internal/proxyproto --go-grpc_out=./internal/proxyproto
      - task: tidy 