// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
)

type Channel struct {
	ID      int64
	Channel string
	Title   string
	Default bool
}

type User struct {
	ID         uuid.UUID
	Username   string
	GivenName  string
	FamilyName string
	Enabled    bool
}

type UserChannel struct {
	UserID     uuid.UUID
	ChanID     int64
	CanPublish bool
}
